spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  redis:
    host:
    port:
    password:
    timeout:
  rabbitmq:
    host:
    port:
    username:
    password:
    virtual-host:

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
