spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
    max-idle:
    max-wait:
    min-idle:
    initial-size:
  redis:
    host:
    port:
    password:
    timeout:
  rabbitmq:
    host:
    port:
    username:
    password:
  data:
    solr:
      host:

server:
  port: 8080
  session:
    timeout:: 10
  tomcat:
    uri-encoding: UTF-8
